# Introducción a PyTorch

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)]()

## Tensores

Un tensor es un objeto matemático que generaliza conceptos como escalares, vectores y matrices para representar relaciones entre múltiples direcciones en un espacio.

En Aprendizaje automático profundo, lo vamos a utilizar como sinónimo de **array multidimensional**. 

El escalar es un tensor de orden 0, un vector es un tensor de orden 1, una matriz uno de orden 2, y podemos generalizarlo para un tensor de orden n. 

Un tensor tiene componentes y transforma de manera especifica. En PyTorch, existen muchas maneras diferentes de crear tensores y un conjunto amplio de métodos y funciones para operar con ellos. Algunas funciones para generar tensores:

In [1]:
import torch

# Desde lista
a = torch.tensor([1, 2, 3])

# Ceros / unos
b = torch.zeros(2, 3)
c = torch.ones(2, 3)

# Aleatorio
d = torch.rand(2, 3)

# Rango
e = torch.arange(0, 10)

### Propiedades básicas de los tensores en PyTorch

In [ ]:
# imprimir tamaño, tipo de dato y dispositivo
print(a.shape)      # tamaño
print(a.dtype)      # tipo de dato
print(a.device)     # CPU o GPU

torch.Size([3])
torch.int64
cpu


### Operaciones básicas

Podemos hacer aritmética elemento a elemento entre tensores:

In [7]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

# hacer x + y, x - y, x * y, x / y
print(x + y)  # suma
print(x - y)  # resta
print(x * y)  # multiplicación
print(x / y)  # división

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])
tensor([0.2500, 0.4000, 0.5000])


También permite directamente la operación con escalares de manera intuitiva y sencilla

In [8]:
x * 2

tensor([2., 4., 6.])

In [9]:
y + 10

tensor([14., 15., 16.])

Una operación muy importante y utilizada en PyTorch es el `boradcasting` en donde se expanden dimensiones de tensores para poder operar con ellos automáticamente (siempre tener cuidado con esto)

In [17]:
x = torch.randint(0, 10, (2, 3))
print('x:', x)
print('x.shape:', x.shape)

y = torch.randint(0, 10, (3,))
print('y:', y)
print('y.shape:', y.shape)

z = x + y  # y se “expande”
print(z)

x: tensor([[2, 7, 8],
        [5, 5, 1]])
x.shape: torch.Size([2, 3])
y: tensor([6, 2, 4])
y.shape: torch.Size([3])
tensor([[ 8,  9, 12],
        [11,  7,  5]])


El broadcasting sucede para todas las operaciones básicas.

También podemos elegir elementos de tensores mediante índices y lo que se conoce como `slicing`

In [21]:
x = torch.tensor([[1, 2, 3, 5],
                  [4, 5, 6, 7]])

print(x[0, 1])     # 2
print(x[:, 1])     # columna
print(x[1, :])     # fila
print(x[1, 0:2])  # elementos 0 y 1 de la fila 1
print(x[1,0::2]) # elementos 0 y 2 de la fila 1

tensor(2)
tensor([2, 5])
tensor([4, 5, 6, 7])
tensor([4, 5])
tensor([4, 6])


Cuando tratamos con multiplicaciones matriciales, existe tanto función como operación básica que permite realizar la operación:

In [24]:
A = torch.rand(2, 3)
B = torch.rand(3, 4)

C = torch.matmul(A, B)

C_bis = A @ B

print(C)
print(C_bis)
print(torch.allclose(C, C_bis)) 

tensor([[1.2335, 1.3969, 1.1392, 1.8715],
        [1.0250, 1.4183, 1.1348, 1.4496]])
tensor([[1.2335, 1.3969, 1.1392, 1.8715],
        [1.0250, 1.4183, 1.1348, 1.4496]])
True


También podemos obtener la transpuesta de una matriz fácilmente con

In [ ]:
A.T

tensor([[0.2911, 0.9550],
        [0.8669, 0.4962],
        [0.9633, 0.1489]])

### Métodos implícitos en tensores muy útiles

Los tensores de PyTorch también tienen métodos inherentes que permiten operaciones sencillas muy utilizadas, como la suma de las componentes, el valor medio, máximo, mínimo, desvío estándar, etc. Estas operaciones se pueden hacer para todo el tensor o para algunas componentes del mismo, seleccionando la dimensión sobre la cuál se desea hacer.

In [29]:
x = torch.rand(2, 3)
print(x)

print('suma', x.sum())
print('media', x.mean())
print('máximo', x.max())
print('mínimo', x.min())
print('desviación estándar', x.std())

# por dimensión
print('suma por columnas', x.sum(dim=0))
print('media por filas', x.mean(dim=1))

tensor([[0.2407, 0.7426, 0.2729],
        [0.7252, 0.7869, 0.3378]])
suma tensor(3.1060)
media tensor(0.5177)
máximo tensor(0.7869)
mínimo tensor(0.2407)
desviación estándar tensor(0.2589)
suma por columnas tensor([0.9659, 1.5295, 0.6107])
media por filas tensor([0.4187, 0.6166])


### Cambiar forma

A veces es necesario ver a los datos en distintas representaciones tensoriales.  

In [30]:
x = torch.arange(6)

x = x.reshape(2, 3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [32]:
x.view(3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

### Concatenación

a veces resulta importante unir dos tensores de manera específica para representarlos en un tensor de mayor dimensión

In [36]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print('concatenación por filas \n', torch.cat([a, b], dim=0))
print('concatenación por columnas \n', torch.cat([a, b], dim=1))

concatenación por filas 
 tensor([[0.7089, 0.8001, 0.4241],
        [0.2969, 0.1895, 0.7835],
        [0.4591, 0.4791, 0.7974],
        [0.4516, 0.8575, 0.8836]])
concatenación por columnas 
 tensor([[0.7089, 0.8001, 0.4241, 0.4591, 0.4791, 0.7974],
        [0.2969, 0.1895, 0.7835, 0.4516, 0.8575, 0.8836]])


tabién se puede lograr con hstack y vstack

In [38]:
print('concatenación por filas \n', torch.vstack([a, b]))  # filas
print('concatenación por columnas \n', torch.hstack([a, b]))  # columnas

concatenación por filas 
 tensor([[0.7089, 0.8001, 0.4241],
        [0.2969, 0.1895, 0.7835],
        [0.4591, 0.4791, 0.7974],
        [0.4516, 0.8575, 0.8836]])
concatenación por columnas 
 tensor([[0.7089, 0.8001, 0.4241, 0.4591, 0.4791, 0.7974],
        [0.2969, 0.1895, 0.7835, 0.4516, 0.8575, 0.8836]])


### Cambio de dispostivo dónde realizar los cómputos

A veces querremos trabajar con los procesadores de la GPU. Para esto, todo tensor involucrado en la operación debe estar previamente en la GPU. PyTorch ofrece el método `.to()` para mover tensores de la CPU a la GPU de manera sencilla. 

In [40]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.rand(3, 3).to(device)
print(x.device)

cpu


In [54]:
import time

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Usando:", device)

Usando: cpu


In [ ]:
N = 3000
A_cpu = torch.rand(N, N)
B_cpu = torch.rand(N, N)

# ---- CPU timing ----
start = time.perf_counter()
C_cpu = A_cpu @ B_cpu
end = time.perf_counter()

cpu_time = end - start
print(f"CPU time: {cpu_time:.4f} seconds")

if torch.cuda.is_available():
    # ---- GPU timing ----
    A_gpu = A_cpu.to(device)
    B_gpu = B_cpu.to(device)

    # Warm-up: evita medir la sobrecarga de la primera operación en GPU
    _ = A_gpu @ B_gpu
    torch.mps.synchronize()

    start = time.perf_counter()
    C_gpu = A_gpu @ B_gpu
    torch.mps.synchronize()
    end = time.perf_counter()

    gpu_time = end - start
    print(f"GPU time: {gpu_time:.4f} seconds")
    print(f"Speedup: {cpu_time / gpu_time:.2f}x")
else:
    print("GPU no disponible, solo se midió el tiempo en CPU.")


CPU time: 0.0648 seconds
GPU no disponible, solo se midió el tiempo en CPU.


## Grafos computacionales dinámicos: gráfos acíclicos direccionados

En PyTorch, podemos definir que un tensor mantenga información de cómo cambia el resultado final de una operación que involucra este tensor, con respecto a este tensor. Para ello almacenamos junto al tensor, su gradiente calculado. Esto se puede hacer de la siguiente manera: 

In [114]:
x = torch.tensor([3.0], requires_grad=True)
y = x**2
z = 7*y

Luego de esta operación, como `requires_grad=True`, PyTorch construye un grafo acíclico direccionado, que mantiene la relación

$$
x \rightarrow y=x^2 \rightarrow z=7y
$$

donde en cada operación se guarda como se calculó y como derivar respecto a la variable, siguiendo al regla de la cadena.

In [115]:
#dy/dx = 2x, si x=3, dy/dx = 6
y.backward(retain_graph=True) #dy/dx se almacena en x.grad
print(x.grad)

tensor([6.])


Recordar resetear el gradiente en el medio, sino se acumulan los valores

In [116]:
x.grad.zero_()
z.backward() #dz/dx = dz/dy * dy/dx = 7 * 2*3 = 42
print(x.grad)

tensor([42.])


Veamos un ejemplo cuando tenemos más que un escalar, en este caso ya se trabaja con un jacobiano

In [ ]:
x = torch.tensor([ 3.0, 2.0], requires_grad=True)
y = x * 2
z = y.sum()
z.backward()
print(x.grad)

tensor([2., 2.])


Lo mismo si tenemos distintas variables

In [ ]:
# Creat tensores
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
# realizar una operación
z = x * y + y ** 2
# retropropagación
z.backward()
# Gradientes
def mostrar_gradientes():
    print(f'dz/dx: {x.grad}')  # Output: 3.0
    print(f'dz/dy: {y.grad}')  # Output: 8.0
mostrar_gradientes()

dz/dx: 3.0
dz/dy: 8.0


En este ejemplo, PyTorch construye un gráfico dinámico a medida que se van ejecutando las operaciones. la función `backward()` computa los gradientes automáticamente utilizando el grafo. Una vez que se utilizó para computar el gradiente, el grafo es eliminado de la memoria, a menos que se explicite lo contrario. 